### ISSUE TITLE
Name of the governance organization

### ISSUE THREAD

**Issue by tracykteal** [carpentries/2017Merger#11]
There has been some confusion about the name of the governing organization for the Carpentries. As a fiscally sponsored project, the name of this governance organization cannot be "board" or "board of directors" because in the United States, where we are a fiscally sponsored project, those terms confer legal fiscal responsibility. Our governing body does not have those legal obligations.

We have been calling our governance for both Software and Data Carpentry "Steering Committee". We are using that term now for the election, but the name can be changed once the new governance body is in place. 

This issue is to answer any questions about this, and get suggestions for other potential names.

**Comment by tracykteal** [comment]
@ethanwhite suggested "Executive Council"

**Comment by ChristinaLK** [comment]
I like Council Something or Something Council after re-reading the chapter on governance in Jono Bacon's book.  :)

**Comment by kcranston** [comment]
According to @tracykteal , the lawyers are happy with Executive Council and not happy with anything involving 'board'. Sound good to everyone?

**Comment by ethanwhite** [comment]
👍

**Comment by ethanwhite** [comment]
We are now the Executive Council.

**Comment by ethanwhite** [comment]
This should be closed (I apparently don't have permissions).
